[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
style = "Bold"
family = "FantasqueSansM Nerd Font"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.offset]
y = 10

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations_theme_variant = "Dark"
opacity = 1.0

[window.dimensions]
columns = 150
lines = 25

[window.padding]
x = 10
y = 10

import = ["~/.config/alacritty/dracula.toml"]
